[package]
name = "sslscan"
version = "1.0.0"
authors = ["Eric Coan <ecoan@instructure.com>"]

[dependencies]
clap = "2"
env_logger = "0.3.4"
lazy_static = "0.2.1"
hyper = "0.9.10"
log = "0.3.6"
rustc-serialize = "0.3.19"
